---
- include: lxd_for_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: lxd_for_centos.yml
  when: 
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"